"""데이터 파이프라인. 3단계로 나눠 각각 따로 검증한다.

  filter    : 원본 gz -> 걸러낸 문서 (라이선스/문법/중복)
  tokenizer : 걸러낸 문서 표본으로 BPE 학습
  tokenize  : 전체 문서 -> uint16 토큰 바이너리 (train.bin / val.bin)

품질 필터의 핵심은 ast.parse다. 파이썬이라서 "이 파일이 유효한 코드인가"를
공짜로, 확실하게 판정할 수 있다. 휴리스틱보다 훨씬 강력하다.
"""

from __future__ import annotations

import argparse
import ast
import gzip
import json
import multiprocessing as mp
import sys
from collections import Counter
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np

from tokenizer.bpe import END_OF_TEXT, BPETokenizer

ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = ROOT / "data" / "raw"
PROC_DIR = ROOT / "data" / "processed"
TOKENIZER_PATH = ROOT / "tokenizer" / "tokenizer.json"

# 명확히 퍼미시브한 것만. GPL/AGPL/LGPL/MPL/EPL 계열은 제외한다.
PERMISSIVE = {
    "mit",
    "apache-2.0",
    "bsd-3-clause",
    "bsd-2-clause",
    "isc",
    "unlicense",
    "cc0-1.0",
    "0bsd",
    "zlib",
}

MIN_BYTES = 64
MAX_BYTES = 200_000
MIN_ALPHA_FRAC = 0.25
MAX_LINE_LEN = 1000

VOCAB_SIZE = 16384
VAL_EVERY = 500  # 500개 문서마다 1개를 검증셋으로 뺀다


# ------------------------------------------------------------------ filter


def filter_shard(path_str: str) -> tuple[str, dict]:
    """샤드 하나를 걸러 part 파일로 쓴다. 워커 프로세스에서 돈다."""
    path = Path(path_str)
    out_path = PROC_DIR / f"part-{path.stem}.jsonl.gz"
    stats: Counter[str] = Counter()

    # 코퍼스 안에는 낡은 문법이 섞여 있어 ast.parse가 경고를 쏟는다.
    # 판정에는 영향이 없으므로 조용히 시킨다.
    import warnings

    warnings.simplefilter("ignore", SyntaxWarning)
    warnings.simplefilter("ignore", DeprecationWarning)

    with gzip.open(path, "rt", encoding="utf-8") as fin, gzip.open(
        out_path, "wt", encoding="utf-8"
    ) as fout:
        for line in fin:
            stats["total"] += 1
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                stats["drop_badjson"] += 1
                continue

            if d.get("license") not in PERMISSIVE:
                stats["drop_license"] += 1
                continue
            if str(d.get("autogenerated")) == "True":
                stats["drop_autogen"] += 1
                continue

            content = d.get("content") or ""
            nbytes = len(content.encode("utf-8"))
            if nbytes < MIN_BYTES or nbytes > MAX_BYTES:
                stats["drop_size"] += 1
                continue
            try:
                if float(d.get("alpha_frac", 1.0)) < MIN_ALPHA_FRAC:
                    stats["drop_alpha"] += 1
                    continue
                if float(d.get("line_max", 0)) > MAX_LINE_LEN:
                    stats["drop_longline"] += 1
                    continue
            except (TypeError, ValueError):
                stats["drop_badmeta"] += 1
                continue

            # 유효한 파이썬 3 코드인가. 파이썬 2 전용 파일도 여기서 걸러진다.
            try:
                ast.parse(content)
            except (SyntaxError, ValueError, MemoryError, RecursionError):
                stats["drop_syntax"] += 1
                continue

            stats["kept"] += 1
            stats["kept_bytes"] += nbytes
            fout.write(json.dumps({"h": str(d.get("hash", "")), "c": content}) + "\n")

    return out_path.name, dict(stats)


def cmd_filter(args):
    PROC_DIR.mkdir(parents=True, exist_ok=True)
    shards = sorted(RAW_DIR.glob("*.json.gz"))
    if not shards:
        raise SystemExit(f"원본 샤드가 없다: {RAW_DIR}. 먼저 download.py를 돌릴 것.")

    # 이미 처리한 샤드는 건너뛴다 (샤드를 추가로 받았을 때 재작업 방지)
    todo = [p for p in shards if not (PROC_DIR / f"part-{p.stem}.jsonl.gz").exists()]
    skipped = len(shards) - len(todo)
    if skipped:
        print(f"[filter] 이미 처리됨 {skipped}개 건너뜀")
    if not todo:
        print("[filter] 새로 처리할 샤드가 없다")
        return

    n_proc = min(len(todo), max(1, (mp.cpu_count() or 2) - 1))
    print(f"[filter] 처리할 샤드 {len(todo)}개, 워커 {n_proc}개")

    total: Counter[str] = Counter()
    with mp.Pool(n_proc) as pool:
        for name, st in pool.imap_unordered(filter_shard, [str(p) for p in todo]):
            total.update(st)
            print(f"[filter] {name}: 유지 {st.get('kept', 0):,} / 전체 {st['total']:,}")

    print("\n[filter] 합계")
    kept, tot = total["kept"], total["total"]
    print(f"  전체 문서   : {tot:,}")
    print(f"  유지        : {kept:,} ({100 * kept / max(tot, 1):.1f}%)")
    print(f"  유지 바이트 : {total['kept_bytes'] / 1024**3:.2f} GB")
    print("  탈락 사유:")
    for k in sorted(k for k in total if k.startswith("drop_")):
        print(f"    {k:16s}: {total[k]:,}")


# ------------------------------------------------------------------ tokenizer


def iter_docs(limit_bytes: int | None = None):
    """걸러낸 문서를 순서대로 흘려준다."""
    parts = sorted(PROC_DIR.glob("part-*.jsonl.gz"))
    if not parts:
        raise SystemExit("걸러낸 문서가 없다. 먼저 filter를 돌릴 것.")
    seen = 0
    for p in parts:
        with gzip.open(p, "rt", encoding="utf-8") as f:
            for line in f:
                d = json.loads(line)
                c = d["c"]
                yield d["h"], c
                if limit_bytes is not None:
                    seen += len(c.encode("utf-8"))
                    if seen >= limit_bytes:
                        return


def cmd_tokenizer(args):
    sample_mb = args.sample_mb
    print(f"[tokenizer] 표본 {sample_mb}MB로 BPE 학습 (vocab={VOCAB_SIZE})")
    texts = [c for _, c in iter_docs(limit_bytes=sample_mb * 1024 * 1024)]
    nbytes = sum(len(t.encode("utf-8")) for t in texts)
    print(f"[tokenizer] 문서 {len(texts):,}개 / {nbytes / 1024**2:.1f} MB")

    tok = BPETokenizer.train(texts, vocab_size=VOCAB_SIZE, verbose=True)
    tok.save(TOKENIZER_PATH)

    # 압축률을 실측한다. 코드 기준 3.0 미만이면 뭔가 잘못됐다.
    probe = "".join(texts[:200])
    ratio = len(probe.encode("utf-8")) / len(tok.encode(probe))
    print(f"\n[tokenizer] 저장: {TOKENIZER_PATH}")
    print(f"[tokenizer] vocab={tok.vocab_size:,} (병합 {len(tok.merges):,}, 예약 {tok.n_reserved})")
    print(f"[tokenizer] 압축률: 바이트/토큰 = {ratio:.3f}")
    if ratio < 3.0:
        print("[tokenizer] 경고: 코드 기준으로 압축률이 낮다. 표본을 늘려볼 것.")


# ------------------------------------------------------------------ tokenize

_WORKER_TOK: BPETokenizer | None = None


def _init_worker(tok_path: str):
    global _WORKER_TOK
    _WORKER_TOK = BPETokenizer.load(tok_path)


def _encode_batch(batch: list[str]) -> list[int]:
    """문서 여러 개를 이어서 인코딩한다. 문서 경계에 EOT를 넣는다."""
    assert _WORKER_TOK is not None
    eot = _WORKER_TOK.special_to_id[END_OF_TEXT]
    out: list[int] = []
    for text in batch:
        out.extend(_WORKER_TOK.encode(text, allow_special=False))
        out.append(eot)
    return out


def cmd_tokenize(args):
    if not TOKENIZER_PATH.exists():
        raise SystemExit("토크나이저가 없다. 먼저 tokenizer를 돌릴 것.")
    tok = BPETokenizer.load(TOKENIZER_PATH)
    if tok.vocab_size > 65535:
        raise SystemExit(f"vocab {tok.vocab_size}는 uint16에 안 들어간다")

    train_path = PROC_DIR / "train.bin"
    val_path = PROC_DIR / "val.bin"
    n_proc = args.workers or max(1, (mp.cpu_count() or 2) - 1)
    print(f"[tokenize] 워커 {n_proc}개 (CPU {mp.cpu_count()}코어), vocab={tok.vocab_size:,}", flush=True)

    # 문서를 배치로 묶어 워커에 보낸다. 순서는 유지한다(imap).
    def batches():
        train_batch: list[str] = []
        val_batch: list[str] = []
        for i, (_h, c) in enumerate(_dedup_docs()):
            if i % VAL_EVERY == 0:
                val_batch.append(c)
                if len(val_batch) >= 64:
                    yield ("val", val_batch)
                    val_batch = []
            else:
                train_batch.append(c)
                if len(train_batch) >= 64:
                    yield ("train", train_batch)
                    train_batch = []
        if train_batch:
            yield ("train", train_batch)
        if val_batch:
            yield ("val", val_batch)

    tagged = list(batches()) if args.eager else None
    src = tagged if tagged is not None else batches()

    counts = {"train": 0, "val": 0}
    with open(train_path, "wb") as ftrain, open(val_path, "wb") as fval, mp.Pool(
        n_proc, initializer=_init_worker, initargs=(str(TOKENIZER_PATH),)
    ) as pool:
        pending = []
        for tag, batch in src:
            pending.append((tag, pool.apply_async(_encode_batch, (batch,))))
            if len(pending) >= n_proc * 4:
                _drain(pending, ftrain, fval, counts)
                pending = []
        _drain(pending, ftrain, fval, counts)

    print("\n[tokenize] 완료")
    for tag, path in (("train", train_path), ("val", val_path)):
        mb = path.stat().st_size / 1024**2
        print(f"  {tag}: {counts[tag]:,} 토큰 ({mb:.1f} MB) -> {path.name}")
    total = counts["train"] + counts["val"]
    print(f"  합계: {total:,} 토큰")


def _drain(pending, ftrain, fval, counts):
    for tag, fut in pending:
        ids = fut.get()
        arr = np.asarray(ids, dtype=np.uint16)
        (ftrain if tag == "train" else fval).write(arr.tobytes())
        counts[tag] += len(ids)
        if (counts["train"] + counts["val"]) % 5_000_000 < len(ids):
            print(f"[tokenize] 누적 {counts['train'] + counts['val']:,} 토큰", flush=True)


def _dedup_docs():
    """해시 기준 전역 중복 제거. 샤드 사이 중복까지 잡는다."""
    seen: set[str] = set()
    dupes = 0
    for h, c in iter_docs():
        if h and h in seen:
            dupes += 1
            continue
        if h:
            seen.add(h)
        yield h, c
    print(f"[dedup] 중복 {dupes:,}개 제거, 고유 {len(seen):,}개")


# ------------------------------------------------------------------ main


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("filter")

    p_tok = sub.add_parser("tokenizer")
    p_tok.add_argument("--sample-mb", type=int, default=100)

    p_tz = sub.add_parser("tokenize")
    p_tz.add_argument("--eager", action="store_true", help="배치를 미리 다 만든다(디버깅용)")
    p_tz.add_argument(
        "--workers", type=int, default=None, help="워커 수 (기본: CPU-1). 다른 작업에 여유를 줄 때 낮춘다"
    )

    args = ap.parse_args()
    {"filter": cmd_filter, "tokenizer": cmd_tokenizer, "tokenize": cmd_tokenize}[
        args.cmd
    ](args)


if __name__ == "__main__":
    main()
